# Generated by Django 5.0.6 on 2024-10-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CensusData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=10)),
                ("dob", models.DateField()),
                ("marital_status", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("division", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("household_members", models.IntegerField()),
                (
                    "household_income",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("head_of_household", models.BooleanField()),
                ("employment_status", models.CharField(max_length=50)),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                ("work_sector", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("highest_education", models.CharField(max_length=50)),
                (
                    "field_of_study",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("currently_enrolled", models.BooleanField()),
                ("house_type", models.CharField(max_length=50)),
                ("house_size", models.IntegerField()),
                ("utilities_available", models.CharField(max_length=255)),
                ("housing_condition", models.CharField(max_length=50)),
            ],
        ),
    ]
