# Generated by Django 5.0.6 on 2024-11-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="censusdata",
            name="id",
        ),
        migrations.AddField(
            model_name="censusdata",
            name="nid_or_birth",
            field=models.DecimalField(
                decimal_places=2,
                default=1234567890,
                max_digits=20,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
