# Generated by Django 5.0.6 on 2024-11-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0003_alter_censusdata_nid_or_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="censusdata",
            name="currently_enrolled",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="censusdata",
            name="head_of_household",
            field=models.CharField(max_length=50),
        ),
    ]
