# Generated by Django 5.0.6 on 2024-12-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_alter_censusdata_currently_enrolled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusdata',
            name='living_area',
            field=models.CharField(default='Urban', max_length=17),
            preserve_default=False,
        ),
    ]
