# Generated by Django 5.0.6 on 2024-12-17 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0005_censusdata_living_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='censusdata',
            name='user',
            field=models.ForeignKey(default=38, on_delete=django.db.models.deletion.CASCADE, related_name='census_entries', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
