# Generated by Django 5.0.6 on 2024-12-17 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0006_censusdata_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusdata',
            name='currently_enrolled',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='censusdata',
            name='head_of_household',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='censusdata',
            name='living_area',
            field=models.TextField(max_length=17),
        ),
        migrations.AlterField(
            model_name='censusdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='census_entry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='censusdata',
            name='utilities_available',
            field=models.TextField(max_length=255),
        ),
    ]
