# Generated by Django 5.2.3 on 2025-06-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0007_alter_censusdata_currently_enrolled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusdata',
            name='currently_enrolled',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='censusdata',
            name='head_of_household',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='censusdata',
            name='living_area',
            field=models.CharField(max_length=17),
        ),
    ]
